### PR TITLE
chore: typo in README.md

### PR DESCRIPTION
**Pull request by pablogamboa**
s/security_polcy/security_policy/g

### CODE REVIEW

**Comment by imrannayer** [comment]
@pablogamboa can you plz sign CLA?

**Comment by pablogamboa** [comment]
@imrannayer I've signed it already, is it still showing up as not signed?

**Comment by apeabody** [comment]
@pablogamboa Thanks!

@imrannayer - I forced a rescan.

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @pablogamboa!

**Pull request merged**
