### PR TITLE
Updating supported load balancer types

### PR DESCRIPTION
**Pull request by cherriford**
Updated for clarity per linked documentation: https://cloud.google.com/armor/docs/cloud-armor-overview#security_policies

### CODE REVIEW

**Comment by imrannayer** [comment]
@cherriford thx for the PR. Documentation is correct. Root module creates global backend security policy which can attach to those 4 load balancers mentioned in the doc. 

For regional external/internal application load balancer there will be a new sub-module available soon PR #126. 

For external pass through Network load balancer you have to first enable Advanced DDoS protection using [Advanced DDoS sub-module](https://github.com/GoogleCloudPlatform/terraform-google-cloud-armor/tree/main/modules/advanced-network-ddos-protection) and create network edge policy using [network edge policy sub-module](https://github.com/GoogleCloudPlatform/terraform-google-cloud-armor/tree/main/modules/network-edge-security-policy). It is mentioned in the the Note section of the root module doc. 
image

**Comment by cherriford** [comment]
Nice! And I can see PR #126 was submitted. Thank you so much!

**Comment by cherriford** [comment]
@imrannayer - Quick question: For the regional backend service module, the `region` value has a description of: `The region in which security policy is created.` Does this mean that the security policy can only be attached to regional load balancers belonging to the same region?

For example, I have 3 regional external application load balancers in a single project; each in a separate region (us-west1, uscentral1, and us-east4). I want all 3 of these load balancers to use the same security policy. Is that possible here?

Thanks!
Cherriford

**Comment by imrannayer** [comment]
I thin you will have to create security policy in each of the region. 

https://cloud.google.com/armor/docs/example-policies#regional-policies

**Pull request closed without merging**
